apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks1
  region: us-east-1

managedNodeGroups:
  - name: djl-sdxl-1
    labels: { model: sdxl }
    amiFamily: AmazonLinux2
    ami: ami-088af3f02047229d4
    instanceType: inf2.xlarge
    desiredCapacity: 1
    volumeSize: 300
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eks1
