apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bern-ml2-eks
  region: us-east-2

managedNodeGroups:
  - name: djl-sdxl
    labels: { model: sdxl }
    amiFamily: AmazonLinux2
    ami: ami-088af3f02047229d4
    instanceType: inf2.xlarge
    desiredCapacity: 1
    ssh: 
      publicKeyName: BernKeyPair-ohio
    volumeSize: 300
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh bern-ml2-eks
